### ISSUE TITLE
Move package installations from Kickstart to provisioning script

### ISSUE THREAD

**Issue by benfairless** [LandRegistry-Ops/packer-lr-centos#3]
Due to Packer using a base AMI when building AWS templates, the step which installs wget, bind-utils etc. as part of the kickstart is skipped. I suggest we move this installation into a provisioning script to provide a more like-for-like template on AWS.

**Comment by stevechambers** [comment]
Agreed - a new packages script will be included and run as a provisioner against all builds (inc AWS)

**Comment by benfairless** [comment]
Is this fixed in 0.3.0?

**Comment by stevechambers** [comment]
Yes
